### ISSUE TITLE
Archive the metadata for old chromium versions

### ISSUE THREAD

**Issue by flotwig** [cypress-io/chromium-downloads#17]
Currently the tool just indexes the latest downloads from omahaproxy.appspot.com, meaning that the versions only go back 3-4 major versions at a time.

It would be nice to cache and build up a list of this metadata so that we can build a large backlog of available Chromium versions.

**Comment by jennifer-shehane** [comment]
Yah. I need to go further back. 😄 	

![](https://media.giphy.com/media/xsF1FSDbjguis/giphy.gif)

**Comment by flotwig** [comment]
Added, should now start archiving old versions as new ones are released.
