### ISSUE TITLE
Error fetching builds from chromium-downloads.herokuapp.com due to unknown error

### ISSUE THREAD

**Issue by mattelen** [cypress-io/chromium-downloads#19]
When you visit https://chromium.cypress.io/, there is an error loading releases. This appears to be the case because the website where it gets the releases, chromium-downloads.herokuapp.com, seems to be broken. I'm assuming that this herokuapp.com is the backend for this website?

**Comment by ChaosCom** [comment]
To add to the "broken" part:

Access to fetch at 'https://chromium-downloads.herokuapp.com/builds' from origin 'https://chromium.cypress.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by bahmutov** [comment]
Thank you, investigating this

**Comment by bahmutov** [comment]
resolved.
