### ISSUE TITLE
Links for macOS arm aarch

### ISSUE THREAD

**Issue by derRichter** [cypress-io/chromium-downloads#20]
Hello,

great, very helpful project. many thx!

is it possible to integrate/add version and links for macOS arm64 aarch64 and maybe Linux-ARM -version?

greats

**Comment by jennifer-shehane** [comment]
We intend to no longer maintain this service, so we're closing this.

We recommend using an alternative for downloading Chromium like: https://vikyd.github.io/download-chromium-history-version
