### ISSUE TITLE
the chrome devtools has bugs, i want to change the chromium of my chrome

### ISSUE THREAD

**Issue by lanmch** [cypress-io/chromium-downloads#21]
the chrome devtools has bugs, i want to change the chromium of my chrome. But I dont know which file should i download from site 'https://chromium.cypress.io/mac/', and how to change it in chrome.
Hope for help
thanks a lot.

**Comment by jennifer-shehane** [comment]
We intend to no longer maintain this service, so we're closing this.

We recommend using an alternative for downloading Chromium like: https://vikyd.github.io/download-chromium-history-version

**Comment by lanmch** [comment]
您好，我已收到您的邮件，我会尽快给您回复。
