### ISSUE TITLE
Download saying file is dangerous

### ISSUE THREAD

**Issue by myxxmikeyxx** [cypress-io/chromium-downloads#23]
When downgliding: [Chromium 88.0.4324.190 for Windows (x86)](https://chromium.cypress.io/win/stable/88.0.4324.190)
It says the file is dangerous and might be hacked. 
I downloaded the 64 bit version and it didn't say that. I also downloaded many other versions and never got this warning.
I downloaded versions 80 to 98 and never got this warning for any of the 64 bit or 32 bit ones besides this one.
Any idea why or a fix?

**Comment by flotwig** [comment]
@myxxmikeyxx Quite strange, did it send you to https://www.googleapis.com/download/storage/v1/b/chromium-browser-snapshots/o/Win%2F2209%2Fmini_installer.exe?generation=2&alt=media ?

This tool only serves files from Google's servers, so there's not much I can do here. Only thing I can think of is that your AV mistakenly flagged a build as malicious, or you have some clickjacking malware on your computer that downloaded a different `.exe`.

**Comment by myxxmikeyxx** [comment]
I was from that link. I am not really sure what happened but I used a different machine and it worked.
