### ISSUE TITLE
 Can you provide a mirror of the chrome dev version?

### ISSUE THREAD

**Issue by Orange-Jun** [cypress-io/chromium-downloads#25]
# Can you provide a mirror of the chrome dev version?

location https://www.google.cn/intl/en_au/chrome/dev/

![image](https://user-images.githubusercontent.com/42060663/177501053-69328e0d-6846-4a43-b8e7-f9cd30a0cb87.png)

**Comment by jennifer-shehane** [comment]
We intend to no longer maintain this service, so we're closing this.

We recommend using an alternative for downloading Chromium like: https://vikyd.github.io/download-chromium-history-version
