### ISSUE TITLE
Travis CI badge shows "build unknown"

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/chromium-downloads#30]
The [README](https://github.com/cypress-io/chromium-downloads/blob/master/README.md) file contains a badge showing "build unknown" with code:

```text
[![Build Status](https://travis-ci.org/flotwig/chromium-downloads.svg?branch=master)](https://travis-ci.org/flotwig/chromium-downloads)
```

![image](https://github.com/cypress-io/chromium-downloads/assets/66998419/6e605e6a-69e2-4857-8ec6-60827778000f)

https://travis-ci.org/flotwig/chromium-downloads
gives the message

"We couldn't display the repository
flotwig/chromium-downloads"

The domain being addressed is `travis-ci.org` and https://docs.travis-ci.com/user/migrate/open-source-repository-migration states

"Starting June 2021 travis-ci.org is disabled and therefore no longer supported. Please use travis-ci.com."

## Suggestion

Migrate to using GitHub Actions instead of using Travis CI.

**Comment by jennifer-shehane** [comment]
We intend to no longer maintain this service, so we're closing this.

We recommend using an alternative for downloading Chromium like: https://vikyd.github.io/download-chromium-history-version

**Comment by MikeMcC399** [comment]
@jennifer-shehane 

> We intend to no longer maintain this service, so we're closing this.
> 
> We recommend using an alternative for downloading Chromium like: https://vikyd.github.io/download-chromium-history-version

References to the site https://chromium.cypress.io would need to be removed from https://docs.cypress.io in that case.

**Comment by jennifer-shehane** [comment]
Yah I’ve got to followup with that
