### ISSUE TITLE
Multiple critical security vulnerabilities

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/chromium-downloads#31]
```bash
yarn audit
```

and GitHub Dependabot show multiple critical vulnerabilities in this repository.

![image](https://github.com/cypress-io/chromium-downloads/assets/66998419/40f89600-1f15-4bf8-9a27-b3e7fe292516)

## Suggestion

Update dependencies accordingly.

**Comment by MikeMcC399** [comment]
The number of flagged vulnerabilities has increased to 125 in the meantime.

**Comment by jennifer-shehane** [comment]
We intend to no longer maintain this service, so we're closing this.

We recommend using an alternative for downloading Chromium like: https://vikyd.github.io/download-chromium-history-version
