### ISSUE TITLE
Wrong binary for 90.0.4430.93

### ISSUE THREAD

**Issue by marco-eckstein** [cypress-io/chromium-downloads#32]
`chrome-win.zip` from <https://chromium.cypress.io/win64/stable/90.0.4430.93> contains version 90.0.4430.0 (Developer Build) (64-Bit).

**Comment by jennifer-shehane** [comment]
We intend to no longer maintain this service, so we're closing this.

We recommend using an alternative for downloading Chromium like: https://vikyd.github.io/download-chromium-history-version
