### ISSUE TITLE
https://chromium-downloads.chary.us/ certificate expired on Dec 6, 2023

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/chromium-downloads#36]
The About section of this repo links to https://chromium-downloads.chary.us/ which has an expired certificate:

![image](https://github.com/cypress-io/chromium-downloads/assets/66998419/c0d6efcc-b0b2-4b45-8feb-a5d5360df416)

![image](https://github.com/cypress-io/chromium-downloads/assets/66998419/f7f7106d-22d1-4083-aa4e-d3a9720c3055)

**Comment by colebrumley** [comment]
Hi Mike, I've updated the link in the repo about to point to https://chromium.cypress.io and verified that the certificate on that site is current as of today. Thanks for the report!
